import { StyleSheet, Dimensions, StatusBar } from "react-native";

export const banner_styles = StyleSheet.create({
    container: {
      flex: 1,
      minHeight: 110,
      maxHeight: '100%',
      width: '100%',
      justifyContent: 'flex-start',
      alignItems: 'center',
      backgroundColor: 'rgb(135, 31, 31)',
      marginTop: 34,
      paddingTop: 10,
      zIndex: 2,
    },
    text: {
      fontFamily: 'Ubuntu',
      fontSize: 16,
      fontWeight: 'normal',
      color: 'white',
      zIndex: 1,
      marginLeft: 10,
    },
  });

export const styles = StyleSheet.create({
    small_margin: {
        marginTop: 20,
    },
    tab_container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: 10,
      columnGap: 20,
    },
    tab_style: {
      alignItems: 'center',
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      width: '100%',
      borderRadius: 1,
      borderWidth: StyleSheet.hairlineWidth,
      backgroundColor: 'rgb(135, 31, 31)',
      borderColor: 'black',
      marginTop: 30,
      marginBottom: 0,
    },
    tab_button: {
      flexBasis: '32%',
      alignItems: 'center',
      paddingTop: 2,
      paddingBottom: 2,
    },
    tab_text: {
      fontFamily: 'Ubuntu',
      fontWeight: 'normal',
      color: 'white',
      fontSize: 18,
    },
    tab_text_selected: {
      fontFamily: 'Ubuntu',
      fontWeight: 'normal',
      color: '#a7aaad',
      fontSize: 18,
    },
    tab_content: {
      margin: 'auto',
      fontFamily: 'Ubuntu',
      fontSize: 12,
      fontWeight: 'bold',
      paddingBottom: 10,
    },
    scroll_view: {
      paddingTop: StatusBar.currentHeight,
      backgroundColor: 'rgb(135, 31, 31)',
    },
    header_title: {
      fontFamily: 'UbuntuBold',
      color: 'white',
      fontSize: 40,
      fontWeight: 'bold',
      paddingTop: StatusBar.currentHeight + 20,
      paddingBottom: 20,
      textAlign: 'center',
      backgroundColor: 'rgb(135, 31, 31)',
    },
    container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: 30,
      paddingBottom: 30,
      width: Dimensions.get('window').width,
    },
    menu_container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingTop: 20,
      paddingBottom: 10,
    },
    title: {
      fontFamily: 'UbuntuBold',
      margin: 'auto',
      fontSize: 24,
      fontWeight: 'bold',
      textAlign: 'center',
      paddingBottom: 10,
    },
    item_item: {
      fontFamily: 'Ubuntu',
      margin: 'auto',
      fontSize: 18,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    item_description: {
      fontFamily: 'Ubuntu',
      margin: 'auto',
      maxWidth: 300,
      fontSize: 12,
      fontWeight: 'normal',
      textAlign: 'center',
    },
    item_price: {
      fontFamily: 'Ubuntu',
      margin: 'auto',
      fontSize: 12,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    separator: {
      marginVertical: 30,
      height: 1,
      width: '80%',
    },
    small_separator: {
      marginVertical: 2,
      height: 2,
      width: '60%',
    },
  });